version: '3.4'
services:
    auto_2024:
        container_name: auto_2024_trt
        build:
            context: ./docker
            dockerfile: core1_2024.dockerfile
            args:
                - TENSORRT_VERSION=8.6
                - CUDNN_VERSION=8.8
                - PYTHON_VERSION=3.10
        network_mode: host
        runtime: nvidia
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - $HOME/ros2_ws:/root/ros2_ws
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        working_dir: /root/ros2_ws
        tty: true
        command: bash